Completed prep-javascript-objects exercise. - Michael Suh
michael-suh/prep-0122-code-solutions pull request #11
Opened 2022-01-18 01:31 UTC by michael-suh

![objects](https://user-images.githubusercontent.com/97069037/149855374-5aa9ccd0-390a-46e3-978e-e96df6c4b682.png)

2022-01-18 16:18 UTC, thebearingedge requested changes

2022-01-18 16:18 UTC, thebearingedge commented on prep-javascript-objects/main.js
> +console.log("The person's name is:", fullname);
You can retrieve the values of an object's properties using dot notation.

```js
var fullName = person.firstName + ' ' + person.lastName;
```

2022-01-19 00:35 UTC, michael-suh commented on prep-javascript-objects/main.js
> +console.log("The person's name is:", fullname);
![objects-edited](https://user-images.githubusercontent.com/97069037/150041243-bf9e46db-876e-49ee-943a-321b33f089ed.png)

2022-01-19 23:53 UTC, thebearingedge approved these changes

2022-01-20 03:56 UTC, merged